apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticapp
  template:
    metadata:
      labels:
        app: staticapp
    spec:
      containers:
        - name: staticapp
          image: muhsineen/staticapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
