name: Self Hosted Runner 

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  selfhosted-job:
    runs-on: abcd

    steps:
      - name: Create folder locally
        run: |
          mkdir -p /home/ubuntu/testfolder4
          mkdir -p /home/ubuntu/testfolder5
          pwd
          ls

      - name: Verify
        run: |
          pwd
          ls
