name: Self Hosted Runner 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selfhosted-job:
    runs-on: self-hosted

    steps:
      - name: Create folder locally
        run: |
          mkdir -p /home/ubuntu/testfolder2
          pwd
          ls

      - name: Verify
        run: |
          pwd
          ls
